-- ============================================================
-- Seed 020: Subscription Plans
-- Defines the three main subscription tiers for ComplianceForge.
-- ============================================================

INSERT INTO subscription_plans (name, slug, description, tier, pricing_eur_monthly, pricing_eur_annual, max_users, max_frameworks, max_risks, max_vendors, max_storage_gb, features, is_active, sort_order)
VALUES
(
    'Starter',
    'starter',
    'Perfect for small teams getting started with compliance management. Includes core GRC features, basic reporting, and up to 3 frameworks.',
    'starter',
    99.00,
    990.00,
    5,
    3,
    100,
    20,
    5,
    '{
        "core_grc": true,
        "risk_management": true,
        "policy_management": true,
        "basic_reporting": true,
        "advanced_reporting": false,
        "sso": false,
        "api_access": false,
        "custom_branding": false,
        "audit_management": true,
        "vendor_management": true,
        "incident_management": true,
        "evidence_collection": true,
        "framework_mappings": true,
        "continuous_monitoring": false,
        "nis2_module": false,
        "dsr_management": false,
        "workflow_engine": false,
        "integrations": false,
        "priority_support": false,
        "dedicated_csm": false,
        "custom_frameworks": false,
        "data_export": true,
        "email_notifications": true,
        "slack_integration": false,
        "teams_integration": false
    }',
    true,
    1
),
(
    'Professional',
    'professional',
    'For growing organisations that need advanced compliance capabilities. Includes SSO, API access, all report types, and up to 5 frameworks.',
    'professional',
    299.00,
    2990.00,
    25,
    5,
    500,
    100,
    25,
    '{
        "core_grc": true,
        "risk_management": true,
        "policy_management": true,
        "basic_reporting": true,
        "advanced_reporting": true,
        "sso": true,
        "api_access": true,
        "custom_branding": false,
        "audit_management": true,
        "vendor_management": true,
        "incident_management": true,
        "evidence_collection": true,
        "framework_mappings": true,
        "continuous_monitoring": true,
        "nis2_module": true,
        "dsr_management": true,
        "workflow_engine": true,
        "integrations": true,
        "priority_support": true,
        "dedicated_csm": false,
        "custom_frameworks": false,
        "data_export": true,
        "email_notifications": true,
        "slack_integration": true,
        "teams_integration": true
    }',
    true,
    2
),
(
    'Enterprise',
    'enterprise',
    'For large organisations requiring full-featured compliance management. Includes everything in Professional plus custom branding, dedicated CSM, and up to 9 frameworks.',
    'enterprise',
    799.00,
    7990.00,
    100,
    9,
    2000,
    500,
    100,
    '{
        "core_grc": true,
        "risk_management": true,
        "policy_management": true,
        "basic_reporting": true,
        "advanced_reporting": true,
        "sso": true,
        "api_access": true,
        "custom_branding": true,
        "audit_management": true,
        "vendor_management": true,
        "incident_management": true,
        "evidence_collection": true,
        "framework_mappings": true,
        "continuous_monitoring": true,
        "nis2_module": true,
        "dsr_management": true,
        "workflow_engine": true,
        "integrations": true,
        "priority_support": true,
        "dedicated_csm": true,
        "custom_frameworks": true,
        "data_export": true,
        "email_notifications": true,
        "slack_integration": true,
        "teams_integration": true
    }',
    true,
    3
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    tier = EXCLUDED.tier,
    pricing_eur_monthly = EXCLUDED.pricing_eur_monthly,
    pricing_eur_annual = EXCLUDED.pricing_eur_annual,
    max_users = EXCLUDED.max_users,
    max_frameworks = EXCLUDED.max_frameworks,
    max_risks = EXCLUDED.max_risks,
    max_vendors = EXCLUDED.max_vendors,
    max_storage_gb = EXCLUDED.max_storage_gb,
    features = EXCLUDED.features,
    is_active = EXCLUDED.is_active,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();
